// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: depotpb/messages.proto

package depotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_depotpb_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ShoppingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	AssignedBotId string                 `protobuf:"bytes,4,opt,name=assigned_bot_id,json=assignedBotId,proto3" json:"assigned_bot_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingList) Reset() {
	*x = ShoppingList{}
	mi := &file_depotpb_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingList) ProtoMessage() {}

func (x *ShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingList.ProtoReflect.Descriptor instead.
func (*ShoppingList) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShoppingList) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShoppingList) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShoppingList) GetAssignedBotId() string {
	if x != nil {
		return x.AssignedBotId
	}
	return ""
}

func (x *ShoppingList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_depotpb_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_depotpb_messages_proto protoreflect.FileDescriptor

const file_depotpb_messages_proto_rawDesc = "" +
	"\n" +
	"\x16depotpb/messages.proto\x12\adepotpb\"a\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x9e\x01\n" +
	"\fShoppingList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12#\n" +
	"\x05items\x18\x03 \x03(\v2\r.depotpb.ItemR\x05items\x12&\n" +
	"\x0fassigned_bot_id\x18\x04 \x01(\tR\rassignedBotId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"E\n" +
	"\x04Item\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantityB}\n" +
	"\vcom.depotpbB\rMessagesProtoP\x01Z#eda-in-golang/depot/depotpb/depotpb\xa2\x02\x03DXX\xaa\x02\aDepotpb\xca\x02\aDepotpb\xe2\x02\x13Depotpb\\GPBMetadata\xea\x02\aDepotpbb\x06proto3"

var (
	file_depotpb_messages_proto_rawDescOnce sync.Once
	file_depotpb_messages_proto_rawDescData []byte
)

func file_depotpb_messages_proto_rawDescGZIP() []byte {
	file_depotpb_messages_proto_rawDescOnce.Do(func() {
		file_depotpb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_depotpb_messages_proto_rawDesc), len(file_depotpb_messages_proto_rawDesc)))
	})
	return file_depotpb_messages_proto_rawDescData
}

var file_depotpb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_depotpb_messages_proto_goTypes = []any{
	(*OrderItem)(nil),    // 0: depotpb.OrderItem
	(*ShoppingList)(nil), // 1: depotpb.ShoppingList
	(*Item)(nil),         // 2: depotpb.Item
}
var file_depotpb_messages_proto_depIdxs = []int32{
	2, // 0: depotpb.ShoppingList.items:type_name -> depotpb.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_depotpb_messages_proto_init() }
func file_depotpb_messages_proto_init() {
	if File_depotpb_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_depotpb_messages_proto_rawDesc), len(file_depotpb_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depotpb_messages_proto_goTypes,
		DependencyIndexes: file_depotpb_messages_proto_depIdxs,
		MessageInfos:      file_depotpb_messages_proto_msgTypes,
	}.Build()
	File_depotpb_messages_proto = out.File
	file_depotpb_messages_proto_goTypes = nil
	file_depotpb_messages_proto_depIdxs = nil
}
